### ISSUE TITLE
git-workflow-merge-conflicts-lab

### ISSUE THREAD

**Issue by mhdhassan99** [learn-co-curriculum/git-workflow-merge-conflicts-lab#20]
this lab is not working
this is what it says
There was a problem cloning this lesson. Retrying...
Cloning lesson...
Cloning lesson...
Cannot clone this lesson right now. Please try again.

**Comment by lizbur10** [comment]
Hi there - I'm so sorry to hear you're having problems! If you still need help, your best option is to submit a question on [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ). The [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) will be able to help you with this.

Thanks! 💙
