### ISSUE TITLE
Readme was updated only on master branch

### ISSUE THREAD

**Issue by ValerieHMoore** [learn-co-curriculum/git-workflow-merge-conflicts-lab#5]
On 7/15/19, the Readme was updated on the master branch but not on the two other branches the student is supposed to merge. This causes the following error: "CONFLICT (content): Merge conflict in README.md Automatic merge failed; fix conflicts and then commit the result."

Student fix:
The lab is about resolving merge conflicts. Students will need to read through the rest of the lesson and apply their newfound knowledge to resolve the merge conflict in the Readme before resolving the other merge conflict in the lesson. 

Lesson fix: Update the readme on the other two branches. 

Thank you.

**Comment by sgharms** [comment]
Should be fixed as of this a.m.

**Comment by lizbur10** [comment]
This problem does not appear to be fixed for students doing pre-work for the 8/26 cohort: https://github.com/learn-co-students/git-workflow-merge-conflicts-lab-dumbo-web-82619
#staff
