### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Joey0719** [learn-co-curriculum/git-workflow-merge-conflicts-lab#7]
i need help and can't ask a question its not letting me for some reason why???

**Comment by sgharms** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum: the text, the tests, etc. I think this is best addressed via: support@learn.co. This team can verify what's going on with your account, what its permissions are, etc. 

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail.

Thanks! 💙
